# Generated by Django 6.0.1 on 2026-01-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginmodel",
            name="profile",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
