# Generated by Django 6.0.1 on 2026-02-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0004_userprofile_delete_loginmodel_delete_registermodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
                (
                    "profile",
                    models.ImageField(blank=True, null=True, upload_to="profiles/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="registermodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
            ],
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
