# Generated by Django 6.0.1 on 2026-02-17 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0005_loginmodel_registermodel_delete_userprofile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seller_first_name", models.CharField(max_length=100)),
                ("seller_last_name", models.CharField(max_length=100)),
                ("seller_email", models.EmailField(max_length=254)),
                (
                    "seller_phone",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Residential Apartment"),
                            ("villa", "Villa"),
                            ("plot", "Plot / Land"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(max_length=255)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "bedrooms",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3+", "3+")], max_length=10
                    ),
                ),
                (
                    "bathrooms",
                    models.CharField(
                        choices=[("1", "1"), ("2", "2"), ("3+", "3+")], max_length=10
                    ),
                ),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="properties/%Y/%m/%d/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="login.property",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LoginModel",
        ),
        migrations.DeleteModel(
            name="registermodel",
        ),
    ]
