# Generated by Django 6.0.1 on 2026-04-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0006_property_propertyimage_delete_loginmodel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
    ]
