# Generated by Django 6.0.1 on 2026-04-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0007_property_latitude_property_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="propertyimage",
            name="image",
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="content_type",
            field=models.CharField(default="image/jpeg", max_length=50),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="image_data",
            field=models.BinaryField(default=b""),
            preserve_default=False,
        ),
    ]
